baseURL = 'https://thisisjab.github.io/'
languageCode = 'en-us'
title = 'thisisjab'
theme = 'nostyleplease'

taxonomies = { tag = "tags" }

cascade.params = { toc = false, tocBorder = false }

[markup]
  [markup.highlight]
    codeFences         = true
    guessSyntax        = false
    lineNos            = false 
    noClasses          = true
    style = 'catppuccin-frappe'
    # style              = 'modus-vivendi'

  [markup.tableOfContents]
    startLevel = 1
    endLevel   = 3
    ordered    = false

[params]
  style = "css/main.scss"
  
  [params.theme_config]
    appearance        = "auto"
    back_home_text    = "< go back"
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = true 